#!/usr/bin/env python3
"""Generate DaVinci Resolve Edit-page Fusion transitions (.setting) and pack
them into an installable .drfx archive.

Spec distilled from dissecting working packs (see repo docs / session notes):
- A transition is a MacroOperator with MainInput1 (A/outgoing clip),
  MainInput2 (B/incoming clip) and MainOutput1, placed under
  Edit/Transitions/<Pack>/ inside a zip renamed .drfx. No manifest needed;
  the filename (minus .setting) is the Effects Library display name.
- All animation MUST use `time/comp.RenderEnd` expressions (normalized 0..1
  progress) so the transition rescales when trimmed on the timeline.
  Frame-keyed BezierSplines do NOT scale — never use them.
- Stock Fusion tools only (Transform/Dissolve/Blur/Custom) — ResolveFX OFX
  nodes are version-pinned and break across Resolve releases.
- User controls: a Custom tool ("Params") holds numbers; InstanceInputs
  expose them in the Inspector; other tools reference Params.NumberInN in
  expressions. Custom tools ship 4 LUTBezier boilerplate splines.

Usage:
    python3 drfx/make_pack.py                 # build dist/<pack>.drfx
    python3 drfx/make_pack.py --install       # build + copy into Resolve Templates
"""

from __future__ import annotations

import argparse
import os
import sys
import zipfile

PACK_NAME = "URAGH Essentials"
DIST = os.path.join(os.path.dirname(__file__), "..", "dist")

# Normalized progress 0..1 across the transition, whatever its length.
T = "time/comp.RenderEnd"

# ---------------------------------------------------------------------------
# Lua-table emission helpers
# ---------------------------------------------------------------------------

LUT_COLORS = [(204, 0, 0), (0, 204, 0), (0, 0, 204), (180, 180, 180)]


def lut_boilerplate(prefix: str) -> str:
    """The four default linear LUTBezier splines a Custom tool expects."""
    chunks = []
    for i, (r, g, b) in enumerate(LUT_COLORS, start=1):
        chunks.append(f"""\
\t\t\t\t{prefix}LUTIn{i} = LUTBezier {{
\t\t\t\t\tKeyColorSplines = {{
\t\t\t\t\t\t[0] = {{
\t\t\t\t\t\t\t[0] = {{ 0, RH = {{ 0.333333333333333, 0.333333333333333 }} }},
\t\t\t\t\t\t\t[1] = {{ 1, LH = {{ 0.666666666666667, 0.666666666666667 }} }}
\t\t\t\t\t\t}}
\t\t\t\t\t}},
\t\t\t\t\tSplineColor = {{ Red = {r}, Green = {g}, Blue = {b} }},
\t\t\t\t\tNameSet = true,
\t\t\t\t}},""")
    return "\n".join(chunks)


def zoom_punch_setting() -> str:
    """Zoom Punch: A-side accelerates into a zoom, hard cut at the midpoint,
    B-side lands from the same zoom level back to rest. Motion blur from the
    Transforms themselves plus an expression-driven Blur envelope.

    Exposed controls: Zoom Amount (0..1, default 0.35), Blur Amount (0..2).
    """
    # A-side zoom: 1 -> 1+zoom over first half (cubic ease-in: slow, then whip)
    size_a = (
        f"iif({T} < 0.5, 1 + Params.NumberIn1 * ((2*{T})^3), 1 + Params.NumberIn1)"
    )
    # B-side zoom: starts at 1+zoom just after the cut, settles to 1
    # (cubic ease-out of the remaining distance)
    size_b = (
        f"iif({T} < 0.5, 1 + Params.NumberIn1, "
        f"1 + Params.NumberIn1 * ((2*(1-{T}))^3))"
    )
    # blur envelope 0 -> 1 -> 0, peaking at the cut
    envelope = f"iif({T} < 0.5, (2*{T})^3, (2*(1-{T}))^3)"
    # hard switch at midpoint — the punch IS the cut
    mix = f"iif({T} < 0.5, 0, 1)"

    return f"""{{
\tTools = ordered() {{
\t\tZoomPunch = MacroOperator {{
\t\t\tCtrlWZoom = false,
\t\t\tNameSet = true,
\t\t\tInputs = ordered() {{
\t\t\t\tComments = Input {{ Value = "{PACK_NAME} — generated by drfx/make_pack.py", }},
\t\t\t\tMainInput1 = InstanceInput {{
\t\t\t\t\tSourceOp = "XfA",
\t\t\t\t\tSource = "Input",
\t\t\t\t}},
\t\t\t\tMainInput2 = InstanceInput {{
\t\t\t\t\tSourceOp = "XfB",
\t\t\t\t\tSource = "Input",
\t\t\t\t}},
\t\t\t\tInput1 = InstanceInput {{
\t\t\t\t\tSourceOp = "Params",
\t\t\t\t\tSource = "NumberIn1",
\t\t\t\t\tName = "Zoom Amount",
\t\t\t\t\tDefault = 0.35,
\t\t\t\t\tMaxScale = 1,
\t\t\t\t\tPage = "Controls",
\t\t\t\t}},
\t\t\t\tInput2 = InstanceInput {{
\t\t\t\t\tSourceOp = "Params",
\t\t\t\t\tSource = "NumberIn2",
\t\t\t\t\tName = "Blur Amount",
\t\t\t\t\tDefault = 1,
\t\t\t\t\tMaxScale = 2,
\t\t\t\t\tPage = "Controls",
\t\t\t\t}}
\t\t\t}},
\t\t\tOutputs = {{
\t\t\t\tMainOutput1 = InstanceOutput {{
\t\t\t\t\tSourceOp = "PostBlur",
\t\t\t\t\tSource = "Output",
\t\t\t\t}}
\t\t\t}},
\t\t\tViewInfo = GroupInfo {{ Pos = {{ 0, 0 }} }},
\t\t\tTools = ordered() {{
\t\t\t\tParams = Custom {{
\t\t\t\t\tCtrlWShown = false,
\t\t\t\t\tInputs = {{
\t\t\t\t\t\tNumberIn1 = Input {{ Value = 0.35, }},
\t\t\t\t\t\tNumberIn2 = Input {{ Value = 1, }},
\t\t\t\t\t\tNumberIn3 = Input {{
\t\t\t\t\t\t\tValue = 0,
\t\t\t\t\t\t\tExpression = "{envelope}",
\t\t\t\t\t\t}},
\t\t\t\t\t\tNameforNumber1 = Input {{ Value = "Zoom Amount", }},
\t\t\t\t\t\tNameforNumber2 = Input {{ Value = "Blur Amount", }},
\t\t\t\t\t\tNameforNumber3 = Input {{ Value = "Envelope", }},
\t\t\t\t\t\tShowNumber4 = Input {{ Value = 0, }},
\t\t\t\t\t\tShowNumber5 = Input {{ Value = 0, }},
\t\t\t\t\t\tShowNumber6 = Input {{ Value = 0, }},
\t\t\t\t\t\tShowNumber7 = Input {{ Value = 0, }},
\t\t\t\t\t\tShowNumber8 = Input {{ Value = 0, }},
\t\t\t\t\t\tLUTIn1 = Input {{ SourceOp = "ParamsLUTIn1", Source = "Value", }},
\t\t\t\t\t\tLUTIn2 = Input {{ SourceOp = "ParamsLUTIn2", Source = "Value", }},
\t\t\t\t\t\tLUTIn3 = Input {{ SourceOp = "ParamsLUTIn3", Source = "Value", }},
\t\t\t\t\t\tLUTIn4 = Input {{ SourceOp = "ParamsLUTIn4", Source = "Value", }},
\t\t\t\t\t}},
\t\t\t\t\tViewInfo = OperatorInfo {{ Pos = {{ 0, -66 }} }},
\t\t\t\t}},
{lut_boilerplate("Params")}
\t\t\t\tXfA = Transform {{
\t\t\t\t\tCtrlWShown = false,
\t\t\t\t\tInputs = {{
\t\t\t\t\t\tSize = Input {{
\t\t\t\t\t\t\tValue = 1,
\t\t\t\t\t\t\tExpression = "{size_a}",
\t\t\t\t\t\t}},
\t\t\t\t\t\tMotionBlur = Input {{ Value = 1, }},
\t\t\t\t\t\tQuality = Input {{ Value = 5, }},
\t\t\t\t\t\tShutterAngle = Input {{ Value = 270, }},
\t\t\t\t\t}},
\t\t\t\t\tViewInfo = OperatorInfo {{ Pos = {{ -110, 0 }} }},
\t\t\t\t}},
\t\t\t\tXfB = Transform {{
\t\t\t\t\tCtrlWShown = false,
\t\t\t\t\tInputs = {{
\t\t\t\t\t\tSize = Input {{
\t\t\t\t\t\t\tValue = 1,
\t\t\t\t\t\t\tExpression = "{size_b}",
\t\t\t\t\t\t}},
\t\t\t\t\t\tMotionBlur = Input {{ Value = 1, }},
\t\t\t\t\t\tQuality = Input {{ Value = 5, }},
\t\t\t\t\t\tShutterAngle = Input {{ Value = 270, }},
\t\t\t\t\t}},
\t\t\t\t\tViewInfo = OperatorInfo {{ Pos = {{ -110, 66 }} }},
\t\t\t\t}},
\t\t\t\tDissolve1 = Dissolve {{
\t\t\t\t\tTransitions = {{
\t\t\t\t\t\t[0] = "DFTDissolve"
\t\t\t\t\t}},
\t\t\t\t\tCtrlWShown = false,
\t\t\t\t\tInputs = {{
\t\t\t\t\t\tMix = Input {{
\t\t\t\t\t\t\tValue = 0,
\t\t\t\t\t\t\tExpression = "{mix}",
\t\t\t\t\t\t}},
\t\t\t\t\t\tBackground = Input {{
\t\t\t\t\t\t\tSourceOp = "XfA",
\t\t\t\t\t\t\tSource = "Output",
\t\t\t\t\t\t}},
\t\t\t\t\t\tForeground = Input {{
\t\t\t\t\t\t\tSourceOp = "XfB",
\t\t\t\t\t\t\tSource = "Output",
\t\t\t\t\t\t}},
\t\t\t\t\t}},
\t\t\t\t\tViewInfo = OperatorInfo {{ Pos = {{ 0, 33 }} }},
\t\t\t\t}},
\t\t\t\tPostBlur = Blur {{
\t\t\t\t\tCtrlWShown = false,
\t\t\t\t\tInputs = {{
\t\t\t\t\t\tXBlurSize = Input {{
\t\t\t\t\t\t\tValue = 0,
\t\t\t\t\t\t\tExpression = "Params.NumberIn3 * 12 * Params.NumberIn2",
\t\t\t\t\t\t}},
\t\t\t\t\t\tInput = Input {{
\t\t\t\t\t\t\tSourceOp = "Dissolve1",
\t\t\t\t\t\t\tSource = "Output",
\t\t\t\t\t\t}},
\t\t\t\t\t}},
\t\t\t\t\tViewInfo = OperatorInfo {{ Pos = {{ 110, 33 }} }},
\t\t\t\t}}
\t\t\t}},
\t\t}}
\t}}
}}
"""


# Registry: display name -> generator function
TRANSITIONS = {
    "Zoom Punch": zoom_punch_setting,
}


def build_drfx(out_dir: str = DIST) -> str:
    os.makedirs(out_dir, exist_ok=True)
    drfx_path = os.path.join(out_dir, f"{PACK_NAME}.drfx")
    with zipfile.ZipFile(drfx_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, generate in TRANSITIONS.items():
            arcname = f"Edit/Transitions/{PACK_NAME}/{name}.setting"
            zf.writestr(arcname, generate())
    return drfx_path


def templates_dir() -> str:
    return os.path.expanduser(
        "~/Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Templates"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install", action="store_true",
                        help="copy the built .drfx into Resolve's user Templates dir")
    args = parser.parse_args()

    path = build_drfx()
    print(f"built: {path}")
    for name in TRANSITIONS:
        print(f"  - {name}")

    if args.install:
        import shutil

        dest = os.path.join(templates_dir(), os.path.basename(path))
        shutil.copy2(path, dest)
        print(f"installed: {dest}")
        print("Restart Resolve, then look in Effects Library > Video Transitions "
              f"> Fusion Transitions > {PACK_NAME}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
